# -*- coding: utf-8 -*-
"""pull_full_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PWeiA_HkYgh75aJRyN2JxDjUtd14bE_

# Pull Full Football Attendance Data Script

**Before Cell 1:** click the 🔑 **Secrets** icon in the left sidebar → *Add new secret* → Name: `CFBD_API_KEY`, Value: your (new) API key → turn on **Notebook access**.
"""

# CELL 1: load the API key from Colab Secrets
import os
try:
    from google.colab import userdata
    os.environ["CFBD_API_KEY"] = userdata.get("CFBD_API_KEY")
except Exception as e:
    print("Secret missing:", e)

assert os.environ.get("CFBD_API_KEY"), "No key found. Add CFBD_API_KEY in the 🔑 Secrets panel and enable Notebook access."
print("Key loaded.")

"""## Cell 2: the pipeline code (defines functions only, nothing runs yet)"""

import argparse
import os
import sys
import time

import pandas as pd
import requests

CFBD_URL = "https://api.collegefootballdata.com"
OPEN_METEO_URL = "https://archive-api.open-meteo.com/v1/archive"

# ----------------------------- SETTINGS -------------------------
YEARS = [2024, 2025, 2026]        # last two full seasons + current season so far
SEASON_TYPES = ["regular"]
HIGH_CUTOFF = 0.90                # draft threshold for "high attendance"
CUTOFFS_TO_TEST = [0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.00]


# ----------------------------- API HELPERS (from sample script) --------------
def get_headers():
    api_key = os.environ.get("CFBD_API_KEY")
    if not api_key:
        sys.exit("Set the CFBD_API_KEY environment variable first.")
    return {"Authorization": f"Bearer {api_key}"}


def get_games(year, season_type="regular"):
    resp = requests.get(
        f"{CFBD_URL}/games",
        headers=get_headers(),
        params={"year": year, "seasonType": season_type, "classification": "fbs"},
        timeout=60,
    )
    resp.raise_for_status()
    return pd.DataFrame(resp.json())


def get_venues():
    resp = requests.get(f"{CFBD_URL}/venues", headers=get_headers(), timeout=60)
    resp.raise_for_status()
    return pd.DataFrame(resp.json())


def get_weather_for_location(lat, lon, date_str, max_retries=3):
    """Return hourly temperature/precipitation/wind speed for one venue on one date."""
    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": date_str,
        "end_date": date_str,
        "hourly": "temperature_2m,precipitation,windspeed_10m",
        "timezone": "UTC",
    }
    for attempt in range(1, max_retries + 1):
        try:
            resp = requests.get(OPEN_METEO_URL, params=params, timeout=15)
            resp.raise_for_status()
            return resp.json().get("hourly", {})
        except requests.exceptions.RequestException as e:
            print(f"    attempt {attempt} failed for ({lat}, {lon}, {date_str}): {e}")
            time.sleep(2 * attempt)
    print(f"    giving up on ({lat}, {lon}, {date_str}), leaving it blank")
    return {}


def build_weather_table(games_with_coords):
    """One Open-Meteo call per unique (venue, date) pair."""
    unique_locations = games_with_coords[
        ["venueId", "latitude", "longitude", "game_date"]
    ].drop_duplicates()

    total = len(unique_locations)
    rows = []
    for i, (_, loc) in enumerate(unique_locations.iterrows(), start=1):
        if i % 25 == 0 or i == total:
            print(f"    {i}/{total} venue/date combos done")
        hourly = get_weather_for_location(loc["latitude"], loc["longitude"], loc["game_date"])
        rows.append(
            {
                "venueId": loc["venueId"],
                "game_date": loc["game_date"],
                "hourly_times": hourly.get("time", []),
                "hourly_temp": hourly.get("temperature_2m", []),
                "hourly_precip": hourly.get("precipitation", []),
                "hourly_wind": hourly.get("windspeed_10m", []),
            }
        )
        time.sleep(0.3)
    return pd.DataFrame(rows)


def pick_kickoff_weather(row):
    """Use the kickoff hour (0-23, from startDate, UTC) to index into the hourly arrays."""
    if not isinstance(row["hourly_temp"], list) or len(row["hourly_temp"]) < 24:
        return pd.Series({"temperature_c": None, "precip_mm": None, "windspeed_kmh": None})
    kickoff_hour = int(row["startDate"][11:13])
    return pd.Series(
        {
            "temperature_c": row["hourly_temp"][kickoff_hour],
            "precip_mm": row["hourly_precip"][kickoff_hour],
            "windspeed_kmh": row["hourly_wind"][kickoff_hour],
        }
    )


# ----------------------------- Multi-season pipeline --------------------
def pull_all_games(years, season_types):
    parts = []
    for year in years:
        for st in season_types:
            print(f"Pulling {year} {st} games...")
            g = get_games(year, st)
            print(f"  {len(g)} games returned")
            if not g.empty:
                parts.append(g)
    return pd.concat(parts, ignore_index=True)


def add_label(df, cutoff=HIGH_CUTOFF):
    """attendance_pct = attendance / capacity; high_attendance = 1 if pct >= cutoff.
    Label is only defined for non-neutral-site games with valid attendance AND capacity."""
    att = df["attendance"].where(df["attendance"] > 0)
    cap = df["capacity"].where(df["capacity"] > 0)
    df["attendance_pct"] = att / cap

    is_home_game = ~df["neutralSite"].fillna(False).astype(bool)
    labelable = df["attendance_pct"].notna() & is_home_game
    df["high_attendance"] = (
        (df["attendance_pct"] >= cutoff).astype(float).where(labelable).astype("Int64")
    )
    df["flag_missing_attendance"] = att.isna()
    df["flag_missing_capacity"] = cap.isna()
    return df


def build_full_table(years=YEARS, season_types=SEASON_TYPES):
    games = pull_all_games(years, season_types)
    print(f"\nTotal rows pulled: {len(games)}")

    # 1) completed games only (schedules for future games exist but have no attendance/weather)
    if "completed" in games.columns:
        games = games[games["completed"] == True].copy()
    print(f"After keeping completed games: {len(games)}")

    # 2) home team must be FBS (classification filter in the API call can let FCS-home games through)
    if "homeClassification" in games.columns:
        print("Home classification counts:", games["homeClassification"].value_counts().to_dict())
        games = games[games["homeClassification"] == "fbs"].copy()
    print(f"After keeping FBS home teams: {len(games)}")

    print("Pulling venues...")
    venues = get_venues()
    print(f"  {len(venues)} venues")

    merged = games.merge(
        venues, how="left", left_on="venueId", right_on="id", suffixes=("", "_venue")
    )
    merged["game_date"] = merged["startDate"].str[:10]

    has_coords = merged.dropna(subset=["latitude", "longitude", "startDate"])
    n_combos = has_coords[["venueId", "game_date"]].drop_duplicates().shape[0]
    print(f"Pulling weather for {n_combos} unique venue/date combos (about {n_combos * 0.4 / 60:.0f}+ min)...")
    weather_lookup = build_weather_table(has_coords)

    merged = merged.merge(weather_lookup, how="left", on=["venueId", "game_date"])
    merged[["temperature_c", "precip_mm", "windspeed_kmh"]] = merged.apply(
        pick_kickoff_weather, axis=1
    )
    # the hourly arrays are only needed to pick the kickoff hour; drop them to keep the CSV small
    merged = merged.drop(columns=["hourly_times", "hourly_temp", "hourly_precip", "hourly_wind"])

    return add_label(merged)


def report(df):
    print("\n================ SUMMARY ================")
    print(f"Rows: {len(df):,} | Columns: {df.shape[1]}")
    print("Rows per season:", df["season"].value_counts().sort_index().to_dict())
    print(f"Missing attendance: {df['flag_missing_attendance'].mean():.1%}")
    print(f"Missing capacity:   {df['flag_missing_capacity'].mean():.1%}")
    print(f"Missing temperature: {df['temperature_c'].isna().mean():.1%}")
    usable = df[df["high_attendance"].notna()]
    print(f"Labelable home games: {len(usable):,}")
    print("\nattendance_pct summary:")
    print(usable["attendance_pct"].describe(percentiles=[.1, .25, .5, .75, .9]).round(3).to_string())
    print("\nShare of games labeled HIGH at each cutoff:")
    for c in CUTOFFS_TO_TEST:
        print(f"  >= {c:.0%}: {(usable['attendance_pct'] >= c).mean():.1%}")
    print("=========================================\n")

"""## Cell 3: run the pull (takes several minutes: the weather step makes one web call per venue/date)"""

df = build_full_table()          # uses YEARS / SEASON_TYPES / HIGH_CUTOFF settings from Cell 2
report(df)

"""## Cell 4: Define Cutoff
*This code was created to define high attendence*
"""

import matplotlib.pyplot as plt
from IPython.display import display

usable = df[df["high_attendance"].notna()].copy()   \
print(f"{len(usable):,} labelable home games out of {len(df):,} rows\n")

# 1) Peek at rows
display(usable[["season", "week", "homeTeam", "awayTeam", "homeConference",
                "attendance", "capacity", "attendance_pct", "high_attendance"]].head(10))

# 2) Distribution of attendance / capacity -- where do most games sit?
plt.figure(figsize=(9, 4))
plt.hist(usable["attendance_pct"].clip(upper=1.3), bins=40)
plt.axvline(HIGH_CUTOFF, color="red", linestyle="--", label=f"draft cutoff = {HIGH_CUTOFF:.0%}")
plt.xlabel("attendance / capacity (values above 130% clipped for display)")
plt.ylabel("number of games"); plt.title("How full are stadiums?"); plt.legend(); plt.show()

# 3) What share of games is 'high' if we move the cutoff?
sens = pd.DataFrame({"cutoff": CUTOFFS_TO_TEST,
                     "share_high": [(usable["attendance_pct"] >= c).mean() for c in CUTOFFS_TO_TEST]})
sens["share_high"] = (sens["share_high"] * 100).round(1).astype(str) + "%"
print("Class balance by cutoff:"); display(sens)

# 4) Does one cutoff treat all conferences fairly? (ethics point in the brief)
by_conf = (usable.groupby("homeConference")
           .agg(games=("attendance_pct", "size"),
                median_pct=("attendance_pct", "median"),
                share_high=("high_attendance", "mean"))
           .sort_values("median_pct").round(2))
print("By conference (sorted by median fill):"); display(by_conf)

# 5) Season-to-season check
display(usable.groupby("season").agg(games=("attendance_pct", "size"),
                                     median_pct=("attendance_pct", "median"),
                                     share_high=("high_attendance", "mean")).round(2))

# 6) Games above 100% capacity
print(f"Games with attendance above capacity: {(usable['attendance_pct'] > 1).mean():.1%}")

"""## Cell 5: Save the table and Download it"""

os.makedirs("data", exist_ok=True)
df.to_csv("data/full_dataset.csv", index=False)
print("Saved data/full_dataset.csv", df.shape)
try:
    from google.colab import files
    files.download("data/full_dataset.csv")
except Exception:
    pass

df.columns.tolist()

